os:
- linux
language: shell

git:
  depth: 2

branches:
  only:
  - master

services:
- docker

env:
  global:
  - POSTGRES_PASSWORD=secret

before_install:
- make check
- make setup

install:
- make install

script:
- make initialize

notifications:
  email: false
